config/routes.rb
Rails.application.routes.draw do
  get 'messages/new'
  get 'messageboards/index'
  resources :t1s
  resources :projects

  devise_for :users, controllers: {
      omniauth_callbacks: "users/callbacks"
  }

  root "account#index"

  resources :accounts, path: '' do
    resources :peoples
    resources :companies
    resources :administrators

    resources :projects do
	    resources :message_boards, controller: 'messageboards', only: %i[show] do
		    resources :messages
      end

      resources :todo_sets, path: 'todosets' do
        resources :todos do
          resources :comments, module: :todos
        end
        resources :comments, module: :todo_sets
      end
    end
  end

  resources :users, path: '' do
    get '/account', to: 'accounts#show'

    resources :projects do
      resources :todos do
        resources :comments, module: :todos
      end
      resources :todo_sets, path: 'todosets' do
        resources :todos do
          resources :comments, module: :todos
        end
        resources :comments, module: :todo_sets
      end
    end
  end

  resources :todo_sets do
    resources :comments, module: :todo_sets
    resources :todos

    resources :todo_groups, path: "groups", only: %i[create]
    delete '/promote', to: 'todo_groups#destroy'
  end

  resources :todos do
    resources :comments, module: :todos
  end

  resources :comments do
    resources :boosts, module: :comments
  end

  resources :message_boards, controller: 'messageboards', only: %i[show] do
    resources :messages
  end

  resources :messages do
    resources :comments, module: :messages
  end

  resources :boosts, only: [:destroy]
  resources :comments, only: %i[destroy update]
  # resources :projects, only: %i[index create new show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/message.rb
class Message < ApplicationRecord
  include Commentable

  belongs_to :message_board
  belongs_to :user

  has_rich_text :body

  validates :title, presence: true
  validates :body, presence: true
  # validates :category, presence: false, inclusion: { in: %w[announcement fyi heartbeat pitch question]}

  delegate :image, :name, to: :user, prefix: true
end

app/controllers/messages/comments_controller.rb
class Messages::CommentsController < CommentsController
  before_action :set_commentable

  private
  def set_commentable
    @commentable = Message.unscoped.find params[:message_id]
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_project, only: [:new, :show]
  before_action :set_messageboard, only: [:create]
  before_action :set_message, only: [:show]

  def new
    @message = @project.message_board.messages.new
  end

  def show; end

  def create
    @message = @message_board.messages.new message_params
    @message.user = current_user

    @message.save!

    respond_to do |format|
      if @message.save
        format.html do
          redirect_to account_project_message_board_url(current_user.account,@message_board.project, @message_board)
        end

      else
        @project = @message_board.project
        format.html do
           render :new, status: :unprocessable_entity
        end
      end
    end
  end

  protected

  def message_params
    params.require(:message).permit(:body, :title, :category, :status)
  end

  def set_messageboard
    @message_board = MessageBoard.find params[:message_board_id]
  end

  def set_project
    @project = Project.find params[:project_id]
  end

  def set_message
    @message = Message.find params[:id]
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/new.html.erb
<div style="background: #FCFCFB" class="w-5/12 rounded flex justify-center shadow-md items-center p-3 pb-5">
  <svg class="w-4 h-4 text-blue-700 mx-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
    <path d="M7 3a1 1 0 000 2h6a1 1 0 100-2H7zM4 7a1 1 0 011-1h10a1 1 0 110 2H5a1 1 0 01-1-1zM2 11a2 2 0 012-2h12a2 2 0 012 2v4a2 2 0 01-2 2H4a2 2 0 01-2-2v-4z"></path>
  </svg>
  <h1 class="text-blue-700 underline">
    <%= link_to @project.name, [current_user, @project] %> >

    <%= link_to "Message Board", account_project_message_board_path(current_user.account, @project, @project.message_board) %>
  </h1>
</div>


<section
  data-controller="todos notification collapse"
  data-notification-content-value="<%= notice %>"
  style="margin-top: -20px"
  class="bg-white p-2 w-6/12 min-h-screen shadow flex flex-col items-center">

  <div class="flex relative" data-controller="todo-list-display">
    <button
      data-action="click->todo-list-display#toggleContainerVisibility"
      class="rounded-full border px-3 py-2 text-xs todo-list__display-settings flex items-center focus:shadow-outline focus:outline-none">
      All messages
    </button>

    <ul
      data-todo-list-display-target="settingsContainer"
      class="absolute bg-white rounded-md shadow py-2 text--gray hidden" style="width: 250px; top: 40px">

      <li>
        <button class="mt-2 p-1 w-full hover:bg-blue-100 text-center font-medium focus:outline-none">
          All messages
        </button>
      </li>

      <button class="mt-2 p-1 w-full hover:bg-blue-100 text-center focus:outline-none">
        View to-dos as cards
      </button>
    </ul>
  </div>


  <main class="w-full">
    <%= form_for [@project.message_board, @message], html: {class: "flex flex-col items-center"} do |f| %>
      <div class="w-9/12 bg--green h-20">

      <%= f.text_field :title, placeholder: "Pick a title", class: "w-full focus:outline-none w-full h-full text-4xl font-medium text-darker" %>
      </div>

      <section class="w-full p-2 border-b border-gray-300 flex flex-col items-center">
        <div class="w-9/12 border--green">

        <%= f.rich_text_area :body, class: "border-0 w-9/12", placeholder: "write away" %>
        </div>
      </section>

      <footer class="w-9/12 flex mt-5">
        <button class="flex items-center px-3 text-xs text-white py-2 rounded-full bg--green focus:outline-none focus:shadow-outline">
          <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M10 5a1 1 0 011 1v3h3a1 1 0 110 2h-3v3a1 1 0 11-2 0v-3H6a1 1 0 110-2h3V6a1 1 0 011-1z" clip-rule="evenodd"></path>
          </svg>
          Save as draft
        </button>

        <%= link_to "Cancel", :back,  class:"mx-2 border border--green text-sm px-3 py-2 rounded-full text--green" %>
      </footer>
    <% end %>
  </main>

</section>

app/views/messages/show.html.erb
<div style="background: #FCFCFB" class="w-5/12 rounded flex justify-center shadow-md items-center p-3 pb-5">
  <svg class="w-4 h-4 text-blue-700 mx-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
    <path d="M7 3a1 1 0 000 2h6a1 1 0 100-2H7zM4 7a1 1 0 011-1h10a1 1 0 110 2H5a1 1 0 01-1-1zM2 11a2 2 0 012-2h12a2 2 0 012 2v4a2 2 0 01-2 2H4a2 2 0 01-2-2v-4z"></path>
  </svg>
  <h1 class="text-blue-700 underline">
    <%= link_to @project.name, [current_user, @project] %> >

    <%= link_to "Message Board", account_project_message_board_path %>
  </h1>
</div>


<section
  id="<%= dom_id(@message, :show) %>"
  data-controller="todos notification collapse"
  data-notification-show-value="<%= notice.nil? %>"
  style="margin-top: -20px;"
  class="bg-white p-2 w-full md:w-6/12 min-h-screen shadow flex flex-col items-center border-b pb-5 relative">
  <div id="notification" class="notification absolute">
    <div class="bg--black--light p-1 flex rounded-md text-white text-xs px-2">
      <svg class="w-6 h-6 text--green" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path>
      </svg>
      The to-do is in the trash
      <a href="" class="mx-2">View Trash</a>

      <button type="button" data-action="click->notification#hide">hide</button>
    </div>
  </div>


  <aside
    data-controller="settings-container"
    class="flex justify-end px-2 py-2 w-full">
    <button
      data-action="click->settings-container#showContainer"
      class="p-2 border rounded-full focus:outline-none">
      <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
        <path d="M6 10a2 2 0 11-4 0 2 2 0 014 0zM12 10a2 2 0 11-4 0 2 2 0 014 0zM16 12a2 2 0 100-4 2 2 0 000 4z"></path>
      </svg>
    </button>

    <section
      class="absolute bg--blue top-0 right-0 rounded-bl-lg py-3 action-sheet__content z-50 text-white truncate">
      <header class="flex justify-end w-full px-2">
        <aside>
          <button
            data-action="click->settings-container#hideContainer"
            aria-label="close" class="border border-white rounded-full text-white focus:outline-none mt-2 mr-2" style="padding: 0.2rem">
            <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
            </svg>
          </button>
        </aside>
      </header>
    </section>
  </aside>

  <main class="w-full md:w-9/12">
  </main>

  <footer class="w-8/12">
    <section class="w-full" id="comments">
      <% @message.comments.each do |comment| %>
        <%= render 'comments/comment', comment: comment %>
      <% end %>
    </section>

    <div class="rounded-lg bg-body__light flex flex-col items-center justify-center p-3 mt-5">
      <button data-todos-target="information" data-action="click->todos#showDescriptionContainer" class="rounded-lg focus:shadow-outline focus:outline-none bg-white w-full p-1 text-left border border--body prompt">
        Add a comment or upload a file
      </button>

      <section data-todos-target="form description" class="w-full rounded-lg trix-hidden__block-tools">
        <%= turbo_frame_tag "new_comment", src: new_message_comment_path(message_id: @message) %>
      </section>
    </div>
  </footer>

  <hr class="w-full my-2 mt-5">
</section>