config/routes.rb
Rails.application.routes.draw do
  get 'messages/new'
  get 'messageboards/index'
  resources :t1s
  resources :projects

  devise_for :users, controllers: {
      omniauth_callbacks: "users/callbacks"
  }

  root "account#index"

  resources :accounts, path: '' do
    resources :peoples
    resources :companies
    resources :administrators

    resources :projects do
	    resources :message_boards, controller: 'messageboards', only: %i[show] do
		    resources :messages
      end

      resources :todo_sets, path: 'todosets' do
        resources :todos do
          resources :comments, module: :todos
        end
        resources :comments, module: :todo_sets
      end
    end
  end

  resources :users, path: '' do
    get '/account', to: 'accounts#show'

    resources :projects do
      resources :todos do
        resources :comments, module: :todos
      end
      resources :todo_sets, path: 'todosets' do
        resources :todos do
          resources :comments, module: :todos
        end
        resources :comments, module: :todo_sets
      end
    end
  end

  resources :todo_sets do
    resources :comments, module: :todo_sets
    resources :todos

    resources :todo_groups, path: "groups", only: %i[create]
    delete '/promote', to: 'todo_groups#destroy'
  end

  resources :todos do
    resources :comments, module: :todos
  end

  resources :comments do
    resources :boosts, module: :comments
  end

  resources :message_boards, controller: 'messageboards', only: %i[show] do
    resources :messages
  end

  resources :messages do
    resources :comments, module: :messages
  end

  resources :boosts, only: [:destroy]
  resources :comments, only: %i[destroy update]
  # resources :projects, only: %i[index create new show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Boostable

  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  belongs_to :commentable, polymorphic: true
  has_rich_text :content

  validates :content, presence: true

  delegate :name, :email, to: :creator, prefix: true
end

app/controllers/comments/boosts_controller.rb
class Comments::BoostsController < BoostsController
  before_action :set_boostable

  private

  def set_boostable
    @boostable = Comment.find params[:comment_id]
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_comment, only: %i[destroy edit update]

  def new
    @comment = @commentable.comments.new
  end

  def edit; end

  def update
    @comment.update comment_params

    respond_to do |format|
      format.turbo_stream do
        render 'comments/replace'
      end
    end
  end

  def create
    @comment = @commentable.comments.new comment_params
    @comment.creator = current_user
    @comment.save

    respond_to do |format|
      format.turbo_stream
      format.html do
        redirect_back fallback_location: root_path, notice: "Comment was created"
      end
    end
  end

  def destroy
    @commentable = @comment.commentable
    @comment.destroy
    respond_to do |format|
      format.turbo_stream do
        render 'comments/remove'
      end

      format.html do
        redirect_back fallback_location: user_project_path(user_id: current_user, id: @commentable.project), notice: 'Comment was removed'
      end
    end
  end

  private
  def set_project
    @project = Project.find params[:project_id]
  end

  def comment_params
    params.require(:comment).permit :content
  end

  def set_comment
    @comment = Comment.find params[:id]
  end
end

app/controllers/messages/comments_controller.rb
class Messages::CommentsController < CommentsController
  before_action :set_commentable

  private
  def set_commentable
    @commentable = Message.unscoped.find params[:message_id]
  end
end

app/controllers/todo_sets/comments_controller.rb
class TodoSets::CommentsController < CommentsController
  before_action :set_commentable

  private
  def set_commentable
    @commentable = TodoSet.unscoped.find params[:todo_set_id]
  end
end

app/controllers/todos/comments_controller.rb
class Todos::CommentsController < CommentsController
  before_action :set_commentable

  private

  def set_commentable
    @commentable = Todo.find params[:todo_id]
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<%= turbo_frame_tag dom_id(comment) do %>
  <article
    class="rounded-lg bg-body__light flex flex-col items-center justify-between px-4 py-2 my-2 relative trix-hidden__block-tools"
    data-controller="settings-container"
    data-settings-container-target="parent"
  >
    <div
      data-settings-container-target="container"
      class="bg--blue top-0 right-0 rounded-lg rounded-tl-none py-3 action-sheet__content z-50">
      <header class="w-full flex justify-end px-2">
        <button
          data-action="click->settings-container#hideContainer"
          aria-label="close" class="border border-white rounded-full text-white focus:outline-none" style="padding: 0.2rem">
          <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
          </svg>
        </button>
      </header>

      <ul class="text-white text-sm">
        <li class="relative my-1 px-3 py-1 aside__button">
          <%= link_to edit_comment_path(id: comment), class: "w-full flex items-center", data: {"action": "click->settings-container#hideContainerBeforeSubmitting"} do %>
            <span class="inline"><svg class="w-4 h-4" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z"></path></svg></span>
            <span class="inline mx-1">Edit</span>
          <% end %>
        </li>

        <li class="my-1 px-3 py-1 aside__button">
          <%= form_for comment, method: :delete do %>
            <button class="w-full flex items-center focus:outline-none">
              <svg class="w-4 h-4" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd"></path>
              </svg>
              <span class="mx-1">Delete</span>
            </button>
          <% end %>
        </li>

        <li class="my-1 px-3 py-1 aside__button flex items-center truncate">
          <svg class="w-4 h-4" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
            <path d="M9 6a3 3 0 11-6 0 3 3 0 016 0zM17 6a3 3 0 11-6 0 3 3 0 016 0zM12.93 17c.046-.327.07-.66.07-1a6.97 6.97 0 00-1.5-4.33A5 5 0 0119 16v1h-6.07zM6 11a5 5 0 015 5v1H1v-1a5 5 0 015-5z"></path>
          </svg>
          <span class="mx-1"> No one was notified</span>
        </li>
      </ul>
    </div>


    <header class="flex flex-row-reverse w-full">
      <aside class="self-start text--gray flex items-center text--body__lighter">
        <small class="text-sm mx-2">
          <%= comment.created_at.hour %>:<%= comment.created_at.min %>
        </small>

        <button
          data-action="click->settings-container#showContainer"
          class="focus:outline-none">
          <svg class="w-4 h-4" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
            <path d="M6 10a2 2 0 11-4 0 2 2 0 014 0zM12 10a2 2 0 11-4 0 2 2 0 014 0zM16 12a2 2 0 100-4 2 2 0 000 4z"></path>
          </svg>
        </button>
      </aside>
      <main class="w-full flex justify-start flex-col my-2 text-sm">
        <h6 class="text-md text--darker font-medium"><%= comment.creator.email %></h6>
        <p class="text--darker">
          <%= comment.content %>
        </p>
      </main>
    </header>

    <aside
      data-controller="boosts"
      class="w-full flex items-center justify-start relative z-0 flex-wrap">
      <section class="flex flex-wrap" id="<%= dom_id comment, :boosts %>">
        <%= render comment.boosts %>
      </section>

      <%= render "boosts/form", boostable: comment %>

      <button
        data-boosts-target="trigger"
        data-action="click->boosts#showForm"
        class="h-6 w-6 flex items-center justify-center rounded-full bg-white focus:outline-none absolute right-0 bottom-0">
        <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="rocket" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" class="svg-inline--fa fa-rocket fa-w-16 fa-5x w-4 h-4 transform -rotate-90 prompt">
          <path fill="currentColor" d="M505.12019,19.09375c-1.18945-5.53125-6.65819-11-12.207-12.1875C460.716,0,435.507,0,410.40747,0,307.17523,0,245.26909,55.20312,199.05238,128H94.83772c-16.34763.01562-35.55658,11.875-42.88664,26.48438L2.51562,253.29688A28.4,28.4,0,0,0,0,264a24.00867,24.00867,0,0,0,24.00582,24H127.81618l-22.47457,22.46875c-11.36521,11.36133-12.99607,32.25781,0,45.25L156.24582,406.625c11.15623,11.1875,32.15619,13.15625,45.27726,0l22.47457-22.46875V488a24.00867,24.00867,0,0,0,24.00581,24,28.55934,28.55934,0,0,0,10.707-2.51562l98.72834-49.39063c14.62888-7.29687,26.50776-26.5,26.50776-42.85937V312.79688c72.59753-46.3125,128.03493-108.40626,128.03493-211.09376C512.07526,76.5,512.07526,51.29688,505.12019,19.09375ZM384.04033,168A40,40,0,1,1,424.05,128,40.02322,40.02322,0,0,1,384.04033,168Z" class=""></path>
        </svg>
      </button>
    </aside>
  </article>
<% end %>

app/views/comments/_form.slim
= form_for [commentable, comment], html: {class: "w-full"} do |f|
  section[class="bg-white p-2 w-full my-2 border border--body rounded-lg"]
    = f.rich_text_area :content, placeholder: "Type your comment here"

  footer[class="w-full flex text-sm"]
    button[type="submit"
      class="button__green px-3 py-2 rounded-full focus:outline-none focus:shadow-outline"
    ] \
      Save Changes

app/views/comments/create.turbo_stream.slim
= turbo_stream.append "comments", partial: "comments/comment", locals: {comment: @comment}

= turbo_stream.replace "comments-count-container" do
  div[
    class="flex items-center justify-center w-3/12"
  ]
    h1[
      id="comments-count"
      class="bg--blue rounded-full h-10 w-10 text-center text-white text-2xl rounded-full"
    ] = @commentable.comments.count

    span class="mx-2 text--darker font-bold" Comments

  hr class="bg-gray-400 w-9/12 ml-3" style="height: 0.5px"/

app/views/comments/edit.html.erb
<%= turbo_frame_tag dom_id(@comment) do %>


  <section class="rounded-lg bg-body__light flex flex-col items-center justify-between px-4 py-2 my-2 trix-hidden__block-tools w-full">
    <%= render "form", comment: @comment, commentable: @commentable, project: @project %>
  </section>
<% end %>

app/views/comments/new.html.erb
<%= turbo_frame_tag "new_comment" do %>
  <%= form_for [@commentable, @commentable.comments.new] do |f|%>
    <section class="bg-white p-2 w-full my-2 border border--body rounded-lg">
      <%= f.rich_text_area :content, placeholder: 'Type your comment here' %>
    </section>

    <button type="submit" class="text-sm button__green px-3 py-2 rounded-full">Add this comment</button>
  <% end %>
<% end %>

app/views/comments/remove.turbo_stream.slim
= turbo_stream.remove dom_id @comment
= turbo_stream.replace "comments-count" do
  h1#comments-count.bg--blue.rounded-full.h-10.w-10.text-center.text-white.text-2xl.rounded-full
    = @commentable.comments.count

app/views/comments/replace.turbo_stream.slim
= turbo_stream.replace dom_id(@comment), @comment