config/routes.rb
Rails.application.routes.draw do
  get 'messages/new'
  get 'messageboards/index'
  resources :t1s
  resources :projects

  devise_for :users, controllers: {
      omniauth_callbacks: "users/callbacks"
  }

  root "account#index"

  resources :accounts, path: '' do
    resources :peoples
    resources :companies
    resources :administrators

    resources :projects do
	    resources :message_boards, controller: 'messageboards', only: %i[show] do
		    resources :messages
      end

      resources :todo_sets, path: 'todosets' do
        resources :todos do
          resources :comments, module: :todos
        end
        resources :comments, module: :todo_sets
      end
    end
  end

  resources :users, path: '' do
    get '/account', to: 'accounts#show'

    resources :projects do
      resources :todos do
        resources :comments, module: :todos
      end
      resources :todo_sets, path: 'todosets' do
        resources :todos do
          resources :comments, module: :todos
        end
        resources :comments, module: :todo_sets
      end
    end
  end

  resources :todo_sets do
    resources :comments, module: :todo_sets
    resources :todos

    resources :todo_groups, path: "groups", only: %i[create]
    delete '/promote', to: 'todo_groups#destroy'
  end

  resources :todos do
    resources :comments, module: :todos
  end

  resources :comments do
    resources :boosts, module: :comments
  end

  resources :message_boards, controller: 'messageboards', only: %i[show] do
    resources :messages
  end

  resources :messages do
    resources :comments, module: :messages
  end

  resources :boosts, only: [:destroy]
  resources :comments, only: %i[destroy update]
  # resources :projects, only: %i[index create new show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  acts_as_tenant :account
  belongs_to :account
  has_one :trash, dependent: :destroy

  has_and_belongs_to_many :people
  has_many :todo_sets, dependent: :destroy

  has_one :message_board
  has_many :messages, through: :message_board

  validates :name, presence: true
  after_create_commit :link_trash
  after_create_commit :create_message_board

  delegate :email, :name, to: :account, prefix: true

  def put_in_trash(entity)
    trash.items.create! trashable: entity
  end

  private

  def link_trash
    Trash.create!(project: self)
  end

  def create_message_board
    MessageBoard.create! project: self
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: %i[edit show update destroy]
  before_action :set_account


  def new
    @project = Project.new
  end

  def index; end

  def create
    @project = @account.projects.new project_params

    respond_to do |format|
      if @project.save
        format.html { redirect_to account_projects_path(account_id: @account), notice: 'Project successfully created.' }
        format.json { render :show, status: :created, location: @t1 }
      else
        format.html { render :new }
        format.json { render json: @t1.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit; end

  def show; end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html do
          redirect_to account_projects_path(account_id: @account), notice: "Project successfuly updated"
        end
      end
    end
  end

  def destroy
    @project.destroy

    respond_to do |format|
      format.html {redirect_to account_projects_path account_id: @account}
    end
  end

  private

  def project_params
    params.require(:project).permit(:name, :description)
  end

  def set_project
    @project = Project.find params[:id]
  end

  def owner?
    current_user.id == Project.find(params[:id]).user_id
  end

  def set_account
    @account = Account.find params[:account_id]
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<div class="bg-white rounded-md shadow p-2 w-7/12 flex flex-col justify-start items-center h-screen">
  <img class="self-center mt-5 mb-1" width="100" height="100" src="https://bc3-production-assets-cdn.basecamp-static.com/assets/logos/paperclip-logo-349bf403c234be9d67457f2825054e138f6d54affe467717f3da909cab741cba.svg" alt="">
  <h1 class="text-2xl text--darker font-medium self-center">
    All right, let’s get your project started!
  </h1>

  <%= form_for @project, html: {class: "flex flex-col my-2 w-full md:w-6/12"} do  |f| %>
    <% if @project.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@project.errors.count, "error") %> prohibited this t1 from being saved:</h2>

        <ul>
          <% @project.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= f.label :name, "Whats your project name", class: "font-medium" %>
    <%= f.text_field :name,  class: "w-full rounded bg-white focus:outline-none focus:shadow-outline border border-gray-500 p-1 my-2", placeholder: "Eg: Rebuild basecamp" %>

    <%= f.label :description, "Any project details?", class: "font-medium mt-2" %>
    <%= f.text_area :description,  class: "w-full rounded bg-white focus:outline-none resize-none focus:shadow-outline border border-gray-500 p-1 my-4", placeholder: "Eg: Rebuild basecamp" %>


    <footer class="flex justify-center mt-2">
      <button type="submit" class="rounded-full p-2 text-white bg--green focus:outline-none focus:shadow-outline">
        Create this project
      </button>
    </footer>
  <% end %>

</div>

app/views/projects/edit.html.erb
<h1>Editing T1</h1>

<%= render 'form', project: @project %>

<!--<%#= link_to 'Show', @t1 %> |-->
<%#= link_to 'Back', t1s_path %>

app/views/projects/index.html.erb
<%#= turbo_frame_tag "rooms", class: "w-full flex flex-col justify-center items-center" do  %>
  <h1 class="mt-5 text-3xl text-center text--darker font-bold">Your Projects</h1>
    <h2 class="text--green">
      <%= notice %>
    </h2>
  <div class="w-full flex flex-col items-center">
    <main class="w-full md:w-4/12 flex flex-col justify-center my-2">
      <% current_user.account.projects.each do |project|  %>
        <%= link_to [@account, project], class: "w-full" do    %>
          <div class="w-full bg-white rounded-md flex flex-col justify-between my-2 h-40 p-2 relative">
            <!--          <div class="absolute flex flex-col bg--blue p-2 text-white w-7/12 side-nav">-->
            <!--            <header class="flex justify-end border-b">-->
            <!--              <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>-->
            <!--            </header>-->


            <!--            <ul class="text-sm">-->
            <!--              <li>-->
            <!--                <button class="my-2">-->
            <!--                  Edit-->
            <!--                </button>-->
            <!--              </li>-->
            <!--              <li class="mb-2">-->
            <!--                <button>-->
            <!--                  Delete-->
            <!--                </button>-->
            <!--              </li>-->
            <!--            </ul>-->
            <!--          </div>-->

            <header class="flex w-full justify-between items-start">
              <div class="w-full">
                <h2 class="font-bold text--darker text-xl">
                  <%= project.name %>
                </h2>

              </div>
            </header>


            <footer>
              <div class="rounded-full h-10 w-10">
                <%= current_user.email %>
              </div>

            </footer>
          </div>
        <% end %>
      <% end %>


      <%= link_to new_account_project_path(account_id: @account), class: "w-full" do %>
        <div class=" bg-white rounded-md flex flex-col justify-center items-center h-40">
          <h2 class="text-2xl">Create new project</h2>

          <svg class="w-10 h-10 text--green" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"></path></svg>
        </div>
      <% end %>
    </main>
  </div>
<%# end %>

app/views/projects/new.html.erb
<div class="bg-white rounded-md shadow p-2 w-7/12 flex flex-col justify-start items-center h-screen">
  <img class="self-center mt-5 mb-1" width="100" height="100" src="https://bc3-production-assets-cdn.basecamp-static.com/assets/logos/paperclip-logo-349bf403c234be9d67457f2825054e138f6d54affe467717f3da909cab741cba.svg" alt="">
  <h1 class="text-2xl text--darker font-medium self-center">
    All right, let’s get your project started!
  </h1>

  <%= form_for [@account, @project], html: {class: "flex flex-col my-2 w-full md:w-6/12"} do  |f| %>
    <% if @project.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@project.errors.count, "error") %> prohibited this t1 from being saved:</h2>

        <ul>
          <% @project.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= f.label :name, "Whats your project name", class: "font-medium" %>
    <%= f.text_field :name,  class: "w-full rounded bg-white focus:outline-none focus:shadow-outline border border-gray-500 p-1 my-2", placeholder: "Eg: Rebuild basecamp" %>

    <%= f.label :description, "Any project details?", class: "font-medium mt-2" %>
    <%= f.text_area :description,  class: "w-full rounded bg-white focus:outline-none resize-none focus:shadow-outline border border-gray-500 p-1 my-4", placeholder: "Eg: Rebuild basecamp" %>


    <footer class="flex justify-center mt-2">
      <button type="submit" class="rounded-full p-2 text-white bg--green focus:outline-none focus:shadow-outline">
        Create this project
      </button>
    </footer>
  <% end %>

</div>

app/views/projects/show.html.erb
<%#= turbo_frame_tag "rooms", class: "w-full" do %>

  <div class="w-6/12 flex flex-col bg-white h-screen">
    <aside class="self-end px-2 py-2">
      <button class="p-2 border rounded-full">
        <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M6 10a2 2 0 11-4 0 2 2 0 014 0zM12 10a2 2 0 11-4 0 2 2 0 014 0zM16 12a2 2 0 100-4 2 2 0 000 4z"></path></svg>
      </button>
    </aside>

    <header class="flex flex-col items-center">
      <h1 class="text-2xl capitalize font-medium text--darker">
        <%= @project.name %>
      </h1>

      <p class="text--gray">
        <%= @project.description %>
      </p>


      <div class="w-full flex justify-center">
        <button class="border rounded-full py-1 text-sm px-3 hover:bg-gray-200">
          Add/Remove people
        </button>
      </div>
    </header>

    <section class="w-full px-10 grid grid-cols-3 my-2">
      <%= link_to account_project_message_board_path(account_id: current_user.account, project_id: @project, id: @project.message_board) do %>
        <article class="flex flex-col justify-center items-center rounded-md border p-2 py-4 mx-2">
          <header class="w-9/12 text-center font-medium text--darker">
            Message Board
          </header>

          <hr class="h-1 my-2 p-1 w-9/12"/>

          <main>
            <div class="bg--blue rounded-full p-2 flex items-center justify-center">
              <svg class="w-12 h-12 text-white" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 13V5a2 2 0 00-2-2H4a2 2 0 00-2 2v8a2 2 0 002 2h3l3 3 3-3h3a2 2 0 002-2zM5 7a1 1 0 011-1h8a1 1 0 110 2H6a1 1 0 01-1-1zm1 3a1 1 0 100 2h3a1 1 0 100-2H6z" clip-rule="evenodd"></path></svg>
            </div>
          </main>

          <footer class="w-9/12 text-sm">

            <p>
              Post announcements, pitch ideas, progress updates, etc. and keep feedback on-topic.
            </p>
          </footer>
        </article>
      <% end %>
      <%= link_to user_project_todo_sets_path(user_id: current_user, project_id: @project) do %>

        <article class="flex flex-col justify-center items-center rounded-md border p-2 py-4 mx-2">
          <header class="w-9/12 text-center font-medium text--darker">
            To-dos
          </header>

          <hr class="h-1 my-2 p-1 w-9/12"/>

          <main>
            <div class="bg--blue rounded-full p-2 flex items-center justify-center">
              <svg class="w-12 h-12 text-white" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 13V5a2 2 0 00-2-2H4a2 2 0 00-2 2v8a2 2 0 002 2h3l3 3 3-3h3a2 2 0 002-2zM5 7a1 1 0 011-1h8a1 1 0 110 2H6a1 1 0 01-1-1zm1 3a1 1 0 100 2h3a1 1 0 100-2H6z" clip-rule="evenodd"></path></svg>
            </div>
          </main>

          <footer class="w-9/12 text-sm">

            <p>
              Post announcements, pitch ideas, progress updates, etc. and keep feedback on-topic.
            </p>
          </footer>
        </article>
      <% end %>

      <a href="">
        <article class="flex flex-col justify-center items-center rounded-md border p-2 py-4 mx-2">
          <header class="w-9/12 text-center font-medium text--darker">
            Docs & Files
          </header>

          <hr class="h-1 my-2 p-1 w-9/12"/>

          <main>
            <div class=" rounded-full p-2 flex items-center justify-center">
              <svg class="w-12 h-12 text--darker" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4 4a2 2 0 012-2h4.586A2 2 0 0112 2.586L15.414 6A2 2 0 0116 7.414V16a2 2 0 01-2 2H6a2 2 0 01-2-2V4z" clip-rule="evenodd"></path></svg>          </div>
          </main>

          <footer class="w-9/12 text-sm">

            <p>
              Post announcements, pitch ideas, progress updates, etc. and keep feedback on-topic.
            </p>
          </footer>
        </article>
      </a>


      <a href="">
        <article class="flex flex-col justify-center items-center rounded-md border p-2 py-4 mx-2 my-4">
          <header class="w-9/12 text-center font-medium text--darker">
            Campfire
          </header>

          <hr class="h-1 my-2 p-1 w-9/12"/>

          <main>
            <div class="bg--blue--light rounded-full p-2 flex items-center justify-center">
              <svg class="w-12 h-12 text-white" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M2 5a2 2 0 012-2h7a2 2 0 012 2v4a2 2 0 01-2 2H9l-3 3v-3H4a2 2 0 01-2-2V5z"></path><path d="M15 7v2a4 4 0 01-4 4H9.828l-1.766 1.767c.28.149.599.233.938.233h2l3 3v-3h2a2 2 0 002-2V9a2 2 0 00-2-2h-1z"></path></svg>          </div>
          </main>

          <footer class="w-11/12 text-sm my-4">

            <p>
              Chat casually with the group, ask random questions, and share stuff without ceremony.
            </p>
          </footer>
        </article>
      </a>



      <a href="">
        <article class="flex flex-col justify-center items-center rounded-md border p-2 py-4 mx-2 my-4">
          <header class="w-9/12 text-center font-medium text--darker">
            Shedule
          </header>

          <hr class="h-1 my-2 p-1 w-9/12"/>

          <main>
            <div style="background: #FF2D55" class="rounded-full p-2 flex items-center justify-center">
              <svg class="w-12 h-12 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"></path></svg>
            </div>
          </main>

          <footer class="w-11/12 text-sm my-4">

            <p>
              Create recurring questions so you don't have to pester your team about what’s going on.
            </p>
          </footer>
        </article>
      </a>

      <a href="">
        <article class="flex flex-col justify-center items-center rounded-md border p-2 py-4 mx-1 my-4">
          <header class="w-9/12 text-center font-medium text--darker">
            Automatic Check-ins
          </header>

          <hr class="h-1 my-2 p-1 w-9/12"/>

          <main>
            <div class="rounded-full p-2 flex items-center justify-center">
              <svg class="w-12 h-12 text-indigo-800" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-8-3a1 1 0 00-.867.5 1 1 0 11-1.731-1A3 3 0 0113 8a3.001 3.001 0 01-2 2.83V11a1 1 0 11-2 0v-1a1 1 0 011-1 1 1 0 100-2zm0 8a1 1 0 100-2 1 1 0 000 2z" clip-rule="evenodd"></path></svg>
            </div>
          </main>

          <footer class="w-11/12 text-sm my-4">

            <p>
              Set important dates on a shared schedule. Subscribe to events in Google Cal, iCal, or Outlook.
            </p>
          </footer>
        </article>
      </a>
    </section>

    <hr class="w-10/12 self-center" />

    <footer class="flex flex-col items-center justify-between">
      <header class="flex flex-col items-center">
        <img class="self-center mt-5 mb-1" width="70" height="70" src="https://bc3-production-assets-cdn.basecamp-static.com/assets/logos/paperclip-logo-349bf403c234be9d67457f2825054e138f6d54affe467717f3da909cab741cba.svg" alt="">
        <h6 class="font-medium text--darker">Welcome to <%= @project.name %>!</h6>
        <small>
          <%= @project.account.email %> created this <%= @project.created_at.strftime("%F") %>
        </small>
      </header>

      <p class="text--gray text-center self-center w-8/12 my-2">
        This is the place to do everything related to this project — make plans, discuss progress, and get work done.
      </p>

      <h6 class="text--gray mt-2">
        Happy Basecamping!
      </h6>
    </footer>
  </div>
<%# end %>