config/routes.rb
Rails.application.routes.draw do
  get 'messages/new'
  get 'messageboards/index'
  resources :t1s
  resources :projects

  devise_for :users, controllers: {
      omniauth_callbacks: "users/callbacks"
  }

  root "account#index"

  resources :accounts, path: '' do
    resources :peoples
    resources :companies
    resources :administrators

    resources :projects do
	    resources :message_boards, controller: 'messageboards', only: %i[show] do
		    resources :messages
      end

      resources :todo_sets, path: 'todosets' do
        resources :todos do
          resources :comments, module: :todos
        end
        resources :comments, module: :todo_sets
      end
    end
  end

  resources :users, path: '' do
    get '/account', to: 'accounts#show'

    resources :projects do
      resources :todos do
        resources :comments, module: :todos
      end
      resources :todo_sets, path: 'todosets' do
        resources :todos do
          resources :comments, module: :todos
        end
        resources :comments, module: :todo_sets
      end
    end
  end

  resources :todo_sets do
    resources :comments, module: :todo_sets
    resources :todos

    resources :todo_groups, path: "groups", only: %i[create]
    delete '/promote', to: 'todo_groups#destroy'
  end

  resources :todos do
    resources :comments, module: :todos
  end

  resources :comments do
    resources :boosts, module: :comments
  end

  resources :message_boards, controller: 'messageboards', only: %i[show] do
    resources :messages
  end

  resources :messages do
    resources :comments, module: :messages
  end

  resources :boosts, only: [:destroy]
  resources :comments, only: %i[destroy update]
  # resources :projects, only: %i[index create new show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  include Account::Administrered

  belongs_to :user
  has_many :companies, dependent: :delete_all
  has_many :people, dependent: :delete_all
  has_many :projects, dependent: :delete_all

  delegate :email, :name, :image, to: :user
end

app/models/account/administratorship.rb
class Account::Administratorship < ApplicationRecord
  belongs_to :person
  belongs_to :account
end

app/models/account/administrered.rb
module Account::Administrered
  extend ActiveSupport::Concern

  included do
    has_many :administratorships do
      def grant(person)
        create_or_find_by person: person
      end

      def revoke(person)
        where(person: person).destroy_all
      end
    end

    has_many :administrators, through: :administratorships, source: :person
  end
end

app/controllers/account_controller.rb
class AccountController < ApplicationController
  before_action :authenticate_user!
  before_action :set_account

  def index
    redirect_to account_projects_path account_id: @account
  end
  private

  def set_account
    @account = Account.find_by_user_id current_user
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def show
    @account = current_user.account
  end
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/show.html.erb
<div class="w-6/12 bg-white flex flex-col justify-start items-center rounded-md h-screen relative">
  <img src="https://bc3-production-assets-cdn.basecamp-static.com/assets/adminland/adminland_bg-97b7840680fa0722709531c4fd307f4e49486e811048c63900c2a17a0608ae85.png" alt="">

  <header class="w-9/12 py-2 flex justify-start items-end absolute top-auto mt-10">
    <div>
      <img width="45" height="45" class="adminland-key img--sized transform" style="transform: rotate(-135deg)" alt="Key" src="https://bc3-production-assets-cdn.basecamp-static.com/assets/icons/basecamp_key_reversed-68613d46b98211b201e3a264c91b0a6adedf121cce10595a8010698ef1bab28d.png">
    </div>
    <div class="flex flex-col">
      <h1 class="text-2xl text--darker font-medium">Adminland</h1>
      <h2 class="text--gray">manager your basecamp account</h2>
    </div>
  </header>

  <section class="w-9/12 flex flex-col mt-10">
    <header>
      <h1 class="text--darker font-medium text-xl">Administrators</h1>
      <h2 class="text--gray text-sm">Your'e an admin, you can do these</h2>
    </header>

    <main class="my-2 p-1 text-sm">
      <ul>
        <li class="w-full color__blue my-2">
          <%= link_to account_peoples_path(account_id: @account), class: "w-full flex items-start" do %>
            <span class="bg--blue rounded-md p-2 text-white">
              <svg class="w-4 h-4" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M9 6a3 3 0 11-6 0 3 3 0 016 0zM17 6a3 3 0 11-6 0 3 3 0 016 0zM12.93 17c.046-.327.07-.66.07-1a6.97 6.97 0 00-1.5-4.33A5 5 0 0119 16v1h-6.07zM6 11a5 5 0 015 5v1H1v-1a5 5 0 015-5z"></path></svg>
            </span>

            <span class="w-full border-b border-gray-300 ml-4 pb-2">
              Add/Remove people or chance thier access
            </span>
          <% end %>
        </li>

        <li class="w-full color__blue my-2">
          <%= link_to account_administrators_path(@account), class: "w-full flex  items-start" do %>
            <span class="bg--blue rounded-md p-2 text-white">
            <svg class="w-4 h-4" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M6 6V5a3 3 0 013-3h2a3 3 0 013 3v1h2a2 2 0 012 2v3.57A22.952 22.952 0 0110 13a22.95 22.95 0 01-8-1.43V8a2 2 0 012-2h2zm2-1a1 1 0 011-1h2a1 1 0 011 1v1H8V5zm1 5a1 1 0 011-1h.01a1 1 0 110 2H10a1 1 0 01-1-1z" clip-rule="evenodd"></path><path d="M2 13.692V16a2 2 0 002 2h12a2 2 0 002-2v-2.308A24.974 24.974 0 0110 15c-2.796 0-5.487-.46-8-1.308z"></path></svg>
            </span>
            <span class="w-full border-b border-gray-300 ml-4 pb-2">
              Add/Remove administrators
            </span>
          <% end %>
        </li>
        <li class="w-full color__blue my-2">
          <%= link_to account_peoples_path(account_id: @account), class: "w-full flex items-start" do %>
            <span class="bg--blue rounded-md p-2 text-white">
<svg viewBox="0 0 36 46" class="w-4 h-4" xmlns="http://www.w3.org/2000/svg"><path d="m31.0031 6.0022c0-.552-.447-1-1-1h-4c-.553 0-1 .448-1 1v4c0 .552.447 1 1 1h4c.553 0 1-.448 1-1zm0 10c0-.552-.447-1-1-1h-4c-.553 0-1 .448-1 1v4c0 .552.447 1 1 1h4c.553 0 1-.448 1-1zm0 10c0-.552-.447-1-1-1h-4c-.553 0-1 .448-1 1v4c0 .552.447 1 1 1h4c.553 0 1-.448 1-1zm-10-20c0-.552-.447-1-1-1h-4c-.553 0-1 .448-1 1v4c0 .552.447 1 1 1h4c.553 0 1-.448 1-1zm0 10c0-.552-.447-1-1-1h-4c-.553 0-1 .448-1 1v4c0 .552.447 1 1 1h4c.553 0 1-.448 1-1zm0 10c0-.552-.447-1-1-1h-4c-.553 0-1 .448-1 1v4c0 .552.447 1 1 1h4c.553 0 1-.448 1-1zm-10-20c0-.552-.447-1-1-1h-4c-.553 0-1 .448-1 1v4c0 .552.447 1 1 1h4c.553 0 1-.448 1-1zm0 10c0-.552-.447-1-1-1h-4c-.553 0-1 .448-1 1v4c0 .552.447 1 1 1h4c.553 0 1-.448 1-1zm0 10c0-.552-.447-1-1-1h-4c-.553 0-1 .448-1 1v4c0 .552.447 1 1 1h4c.553 0 1-.448 1-1zm25-22v38c0 2.206-1.794 4-4 4h-7c-.553 0-1-.448-1-1v-8c0-1.103-.897-2-2-2h-8c-1.103 0-2 .897-2 2v8c0 .552-.447 1-1 1h-7c-2.206 0-4-1.794-4-4v-38c0-2.206 1.794-4 4-4h28c2.206 0 4 1.794 4 4zm-14 34v7c0 .552-.447 1-1 1h-6c-.553 0-1-.448-1-1v-7c0-.552.447-1 1-1h6c.553 0 1 .448 1 1z" fill="#fff" fill-rule="evenodd"/></svg>

            </span>

            <span class="w-full border-b border-gray-300 ml-4 pb-2">
              Rename Or delete a company
            </span>
          <% end %>
        </li>

        <li class="w-full color__blue my-2">
          <%= link_to account_peoples_path(account_id: @account), class: "w-full flex  items-start" do %>
            <span class="bg--blue rounded-md p-2 text-white">
              <svg class="w-4 h-4" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M9 6a3 3 0 11-6 0 3 3 0 016 0zM17 6a3 3 0 11-6 0 3 3 0 016 0zM12.93 17c.046-.327.07-.66.07-1a6.97 6.97 0 00-1.5-4.33A5 5 0 0119 16v1h-6.07zM6 11a5 5 0 015 5v1H1v-1a5 5 0 015-5z"></path></svg>
            </span>

            <span class="w-full border-b border-gray-300 ml-4 pb-2">
              Change message categories
            </span>
          <% end %>
        </li>
      </ul>
    </main>
  </section>

  <section class="w-9/12 flex flex-col">
    <header class="flex flex-col my-5">
      <h1 class="text--darker font-medium text-xl">Account Owners</h1>

      <ul class="text-base">
        <li class="text-sm">
          <%= @account.user.email %>
        </li>
      </ul>
    </header>

    <main>
      <ul class="text-sm">
        <li class="w-full color__blue my-2">
          <%= link_to account_peoples_path(account_id: @account), class: "w-full flex items-start" do %>
            <span class="bg__orange rounded-md p-2 text-white">
              <svg enable-background="new 0 0 267.5 267.5" viewBox="0 0 267.5 267.5" class="w-4 h-4" xmlns="http://www.w3.org/2000/svg"><path d="m256.975 100.34c.041.736-.013 1.485-.198 2.229l-16.5 66c-.832 3.325-3.812 5.663-7.238 5.681l-99 .5c-.013 0-.025 0-.038 0h-99.001c-3.444 0-6.445-2.346-7.277-5.688l-16.5-66.25c-.19-.764-.245-1.534-.197-2.289-6.383-2.011-11.026-7.984-11.026-15.023 0-8.685 7.065-15.75 15.75-15.75s15.75 7.065 15.75 15.75c0 4.891-2.241 9.267-5.75 12.158l20.658 20.814c5.221 5.261 12.466 8.277 19.878 8.277 8.764 0 17.12-4.162 22.382-11.135l33.95-44.984c-2.852-2.85-4.618-6.788-4.618-11.13 0-8.685 7.065-15.75 15.75-15.75s15.75 7.065 15.75 15.75c0 4.212-1.672 8.035-4.375 10.864.009.012.02.022.029.035l33.704 45.108c5.26 7.04 13.646 11.243 22.435 11.243 7.48 0 14.514-2.913 19.803-8.203l20.788-20.788c-3.583-2.89-5.884-7.308-5.884-12.259 0-8.685 7.065-15.75 15.75-15.75s15.75 7.065 15.75 15.75c0 6.851-4.405 12.678-10.525 14.84zm-18.308 97.91c0-4.142-3.358-7.5-7.5-7.5h-194c-4.142 0-7.5 3.358-7.5 7.5v18c0 4.142 3.358 7.5 7.5 7.5h194c4.142 0 7.5-3.358 7.5-7.5z" fill="#fff"/></svg>
            </span>

            <span class="w-full border-b border-gray-300 ml-4 pb-2">
              Upgrade to business
            </span>
          <% end %>
        </li>
        <li class="w-full color__blue my-2">
          <%= link_to account_peoples_path(account_id: @account), class: "w-full flex items-start" do %>
            <span class="bg__orange rounded-md p-2 text-white">
                <svg class="w-4 h-4" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z"></path></svg>
            </span>

            <span class="w-full border-b border-gray-300 ml-4 pb-2">
              Add/Remove account owners
            </span>
          <% end %>
        </li>

        <li class="w-full color__blue my-2">
          <%= link_to account_peoples_path(account_id: @account), class: "w-full flex items-start" do %>
            <span class="bg__orange rounded-md p-2 text-white">
              <svg class="w-4 h-4" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd"></path></svg>
            </span>

            <span class="w-full border-b border-gray-300 ml-4 pb-2">
              View everything in the trash
            </span>
          <% end %>
        </li>

        <li class="w-full color__blue my-2">
          <%= link_to account_peoples_path(account_id: @account), class: "w-full flex items-start" do %>
            <span class="bg__orange rounded-md p-2 text-white">
              <svg class="w-4 h-4" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path clip-rule="evenodd" d="M4 4a2 2 0 00-2 2v8a2 2 0 002 2h12a2 2 0 002-2V8a2 2 0 00-2-2h-5L9 4H4zm7 5a1 1 0 00-2 0v1.586l-.293-.293a.999.999 0 10-1.414 1.414l2 2a.999.999 0 001.414 0l2-2a.999.999 0 10-1.414-1.414l-.293.293V9z" fill-rule="evenodd"></path></svg>
            </span>

            <span class="w-full border-b border-gray-300 ml-4 pb-2">
              Export data from this account
            </span>
          <% end %>
        </li>

        <li class="w-full color__blue my-2">
          <%= link_to account_peoples_path(account_id: @account), class: "w-full flex items-start" do %>
            <span class="bg__orange rounded-md p-2 text-white">
              <svg viewBox="0 0 18 18" class="w-4 h-4" xmlns="http://www.w3.org/2000/svg"><path d="m9 .6c-4.639 0-8.4 3.761-8.4 8.4s3.761 8.4 8.4 8.4 8.4-3.761 8.4-8.4-3.761-8.4-8.4-8.4zm4.789 11.461-1.729 1.729-3.06-3.061-3.061 3.06-1.729-1.729 3.062-3.06-3.061-3.061 1.729-1.728 3.06 3.06 3.061-3.061 1.729 1.729-3.062 3.061z" fill="#fff"/></svg>
            </span>
            <span class="w-full border-b border-gray-300 ml-4 pb-2">
              Cancel this account
            </span>
          <% end %>
        </li>
      </ul>
    </main>
  </section>
</div>